core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy
from django.views.generic import TemplateView

from . import views

app_name = "core"
urlpatterns = [
    path("signup", views.SignupView.as_view(), name="signup"),
    path("user", views.userindex, name="user"),
    path(
        "confirm",
        TemplateView.as_view(template_name="registration/confirm_request.html"),
        name="confirm",
    ),
    path("activate/<slug:uidb64>/<slug:token>/", views.activate, name="activate"),
    path("resend", views.ResendView.as_view(), name="resend"),
    # Forward all other urls to django's default auth system
    # logout, password_reset, etc
    path("", include("django.contrib.auth.urls")),
]

auth_views.PasswordResetConfirmView.success_url = reverse_lazy(
    "core:password_reset_complete"
)
auth_views.PasswordResetView.success_url = reverse_lazy("core:password_reset_done")
auth_views.PasswordChangeView.success_url = reverse_lazy("core:password_change_done")

eval/urls.py
from django.urls import path

from . import views

app_name = "eval"
urlpatterns = [
    path("submit", views.SubmitView.as_view(), name="submit"),
    path(
        "reconstruction",
        views.ReconstructionEntriesView.as_view(),
        name="reconstruction",
    ),
    path("detail/<int:pk>", views.DetailView.as_view(), name="detail"),
    path("compare/", views.CompareView.as_view(), name="compare"),
    path("compare/<int:pk1>/<int:pk2>", views.CompareView.as_view(), name="compare"),
    path("edit/<int:pk>", views.EditView.as_view(), name="edit"),
    path("edit/<int:pk>/delete", views.DeleteEntryView.as_view(), name="delete"),
]

spcwebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from core.views import forward_auth_check

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("accounts/", include("core.urls")),
    path("eval/", include("eval.urls")),
    path("admin/", admin.site.urls),
    path("admin/action-forms/", include("django_admin_action_forms.urls")),
    path(
        "download",
        TemplateView.as_view(template_name="download.html"),
        name="download",
    ),
    path(
        "faq",
        TemplateView.as_view(template_name="faq.html"),
        name="faq",
    ),
    path(
        "competition",
        TemplateView.as_view(template_name="competition.html"),
        name="competition",
    ),
    path("captcha/", include("captcha.urls")),
    path(
        "auth/check/<str:entry_type>/<int:user_pk>/<uuid:entry_uuid>/<path:path>",
        forward_auth_check,
        name="auth-check",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}
    <title>The Single Photon Challenge</title>
    {% endblock %}
    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;600&family=Inter:wght@400;600&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icon.png' %}">
    <meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)">
    <meta name="theme-color" content="#212121" media="(prefers-color-scheme: dark)">
    <!-- Open Graph Protocol tags to enable site preview when sharing -->
    <meta property="og:title" content="The Single Photon Challenge" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://singlephotonchallenge.com/" />
    <meta property="og:image" content="https://singlephotonchallenge.com/static/website-logo.png" />
    <meta property="og:logo" content="https://singlephotonchallenge.com/static/website-logo.png" />
    <meta property="og:description"
        content="Announcing the Single-Photon Challenge -- a first-of-its-kind competition for a fundamental problem in modern imaging: Reconstructing high-quality images from noisy, single-photon data." />
    {% block extra_head %}{% endblock %}
    <!-- to prevent Firefox FOUC, this must be here -->
    <script>(_=>{let a})()</script>
</head>

<body>
    <header>
        <div style="max-width:800px;margin-left: auto; margin-right: auto;margin-top:10px;margin-bottom:0">
            <a href="{% url 'index' %}">
                <picture>
                    <img width="100%" height="156px" max-width="600px" src="{% static 'website-logo.webp' %}"
                        alt="Single Photon Challenge">
                </picture>
            </a>
            <p style="margin-top:0.5rem;margin-bottom:0.5rem;">
                <i>
                    Sacha Jungerman<sup><small>1</small></sup>,
                    Atul Ingle<sup><small>2</small></sup>,
                    Sotiris Nousias<sup><small>3</small></sup>,
                    Mian Wei<sup><small>4</small></sup>,
                    Mel White<sup><small>5</small></sup>,
                    Mohit Gupta<sup><small>1</small></sup>
                </i>
            </p>
            <p style="margin-top:0.5rem;margin-bottom:0.5rem;">
                <i>
                    <sup><small>1</small></sup>University of Wisconsin - Madison,
                    <sup><small>2</small></sup>Portland State University,
                    <sup><small>3</small></sup>Purdue University,
                    </br>
                    <sup><small>4</small></sup>Carnegie Mellon University,
                    <sup><small>5</small></sup>US Naval Research Lab
                </i>
            </p>
        </div>
        <nav>
            <a href="{% url 'download' %}" {% if request.resolver_match.view_name == "download" %}class="current"{% endif %}>Download</a>
            <a href="{% url 'competition' %}" {% if request.resolver_match.view_name == "competition" %}class="current"{% endif %}>Competition</a>
            <a href="{% url 'eval:reconstruction' %}" {% if request.resolver_match.view_name == "eval:reconstruction" %}class="current"{% endif %}>Reconstruction</a>
            <a href="{% url 'eval:submit' %}" {% if request.resolver_match.view_name == "eval:submit" %}class="current"{% endif %}>Submit</a>            
            <a href="https://visionsim.readthedocs.io/en/latest/">VisionSIM Toolkit</a>
            <a href="{% url 'faq' %}" {% if request.resolver_match.view_name == "faq" %}class="current"{% endif %}>FAQ</a>
        </nav>
        <div style="padding: 0 1rem; overflow: hidden;">
            <div style="float:left; text-align: center;">
                {% if user.is_superuser %}
                <a href="{% url 'admin:index' %}">Admin Panel</a> |
                {% endif %}
                {% if user.is_authenticated %}
                <a href="{% url 'core:password_change' %}">Change Password</a>
                {% endif %}
            </div>
            <div style="float:right; text-align: center;">
                {% if user.is_authenticated %}
                <a href="{% url 'core:user' %}">{{ user.get_username }}</a> |
                <form method="post" action="{% url 'core:logout'%}" class="inline">
                    {% csrf_token %}
                    <button type="submit" class="link-button">Logout</button>
                </form>
                {% else %}
                Not logged in | <a href="{% url 'core:login'%}">Login</a> | <a href="{% url 'core:signup'%}">Create
                    Account</a>
                {% endif %}
            </div>
        </div>
    </header>

    <div style="width: 80%; margin: auto;">
        {% block content %}
        {% endblock %}
    </div>

    <div style="flex-grow: 1;"></div>
    <footer>
        <table class="logotable" style="max-width: 1000px;">
            <tr>
                <td style="width:15%;text-align:center" class="noborder"><a href="https://www.wisc.edu/" target="_blank"
                        rel="noopener noreferrer"><img width="90%" src="{% static 'uw-logo.png' %}"
                            alt="Logo of University of Wisconsin - Madison"></a></td>
                <td style="width:15%;text-align:center" class="noborder"><a href="https://cvspc.cs.pdx.edu/"
                        target="_blank" rel="noopener noreferrer"><img width="90%" src="{% static 'ICCV-2025.png' %}"
                            alt="Logo of ICCV 2025"></a></td>
                <td style="width:15%;text-align:center" class="noborder"><a href="https://wisionlab.com/"
                        target="_blank" rel="noopener noreferrer"><img width="90%"
                            src="{% static 'wisionlab-logo.png' %}" alt="Logo of WISION Lab"></a></td>
            </tr>
        </table>
        <table class="logotable" style="margin-top: -1.5rem; width: 40%; max-width: 700px;">
            <tr>
                <td style="width:10%;text-align:center" class="noborder">
                    <a href="https://www.ubicept.com" target="_blank" rel="noopener noreferrer">
                        <picture>
                            <source srcset="{% static 'ubicept_logo_dark.png' %}" media="(prefers-color-scheme: dark)">
                            <img style="width:90%;" src="{% static 'ubicept_logo_light.png' %}" alt="Ubicept">
                        </picture>
                    </a>
                </td>
                <td style="width:10%;text-align:center" class="noborder">
                    <a href="https://singularphotonics.com/" target="_blank" rel="noopener noreferrer">
                        <picture>
                            <source srcset="{% static 'Singular-Photonics-Logo-dark.webp' %}"
                                media="(prefers-color-scheme: dark)">
                            <img style="width:90%;" src="{% static 'Singular-Photonics-Logo-light.webp' %}"
                                alt="Singular Photonics">
                        </picture>
                    </a>
                </td>
            </tr>
        </table>
    </footer>
</body>

</html>

templates/competition.html
{% extends "base.html" %}

{% block content %}

<h3>Competition Guidelines</h3>

<h4>Description</h4>
<p>
    For this image reconstruction challenge, you will need to come up with novel and creative ways to transform many single-photon camera frames into a single high-quality image! This setting is very similar to traditional burst imaging, but taken to the extreme. Instead of a few burst images, you have access to a thousand, but the catch is that each input frame is extremely noisy. Oh, and of course, the scene is dynamic!  
    </br>
    For a very simple implementation please see the <a href="{% url 'faq' %}">FAQ</a>.
</p>

<h4>Timeline</h4>
<p>
    The single photon reconstruction competition is now open! The submission deadline is <b>April 1, 2026 (AOE)</b> and winners will be announced in summer 2026. 
</p>

<h4>Eligibility</h4>
<p>
    Anyone is welcome to participate; however, due to potential conflicts of interest, students and employees affiliated with the organizing committee's labs or the sponsoring companies are encouraged to participate but will not be considered for the final prizes.
</p>

<h4>Participation Requirements</h4>
<p>
    In order to participate in the competition, you must:
    <ul>
        <li>

            Create an account and <a href="{% url 'eval:submit' %}">submit your reconstruction results</a> for evaluation. You may submit results for evaluation as many times as you'd like, but keep in mind that:

            <ol>
                <li>You may only submit your results for evaluation up to 4 times per day,</li>
                <li>And only one submission will count towards the competition.</li> 
            </ol> 
        </li>
        <li>
            Once evaluated (this can take a few hours), ensure you change the visibility of your final submission to "Anonymous"; otherwise, the judges will not be able to view your reconstruction results, and you will be automatically disqualified. Also, make sure to save the submission file, as you will be required to re-upload it in the final step.
        </li>
        <li>
            In a CVPR-formated 4 page document (references excluded) explaining your method, design decision, and any algorithmic considerations. This document will be sent to our judges, who will review it alongside your reconstruction results, so ensure it is properly anonymized!
        </li>
        <li>
            Publish your source code such that it can be publicly viewed; you'll need to submit a link to its repository.     
        </li>
        <li>
            Finally, to formally apply to the competition, upload all these materials <a href="https://forms.gle/UR5x5DwJAQunvpU78">by filling out this form</a>. 
        </li>
    </ul>
</p>

<h4>Judging and Prizes</h4>
<p>
    Submissions will be evaluated by a panel of judges who are experts in the field of single-photon computational imaging. Judges will wholistically consider both reconstruction metrics and qualitative quality, as well as the proposed methodology as described in the submission's whitepaper. Thanks to our sponsors, thousands of dollars in prizes will be awarded!   
</p>

<h4>Intellectual Property and Use of Submissions</h4>
<p>
    Participants retain full ownership of all intellectual property rights, including any copyrights, patents, and other proprietary rights, in and to their submissions.

    By entering the competition, participants grant the organizers a non-exclusive, worldwide, royalty-free, and perpetual license to use, reproduce, publish, share, distribute, and display the submission materials, in whole or in part, for purposes related to the administration, promotion, and operation of the competition and related activities.

    This license does not transfer ownership of the submission and does not restrict participants from using, commercializing, or licensing their submissions independently.
</p>


<h3>Competition FAQ</h3>

<h4>Can I participate in the competition and also publish my work at another conference or journal?</h4>
<p>
    Of course! Your participation in this challenge does not in any way prevent you from publication elsewhere. Your 4-page competition write-up does not constitute a publication, and thus you are free to use it as the basis of a manuscript for another venue. 
    
    In fact, if you do publish your method, consider including (and perhaps even linking to) your single photon benchmark scores, as these provide a standardized metric to compare against.  
</p>

<h4>Can we use additional datasets?</h4>
<p>
    Yes! You may use any datasets you'd like; we just ask that you clearly state which datasets have been used, and that any additional data-wrangling is clearly described.  
</p>

{% endblock %}

templates/download.html
{% extends "base.html" %}

{% block content %}

<link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/stackoverflow-dark.min.css"
    media="(prefers-color-scheme: dark)" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/stackoverflow-light.min.css"
    media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js"></script>
<script>hljs.highlightAll();</script>

<h3>Reconstruction Dataset</h3>

<p>
    The reconstruction dataset (~425G training set + ~42G test set, ~133G and ~13G compressed respectively) consists of
    photoncube/image pairs from 50 unique simulated scenes, plus another 5 scenes for the test set (for which ground
    truths are not made public). Each photoncube consists of 1024 bitplanes, and the associated ground truth
    reconstruction corresponds to the last bitplane. A sample of this dataset can be <a
        href="https://drive.google.com/file/d/1wV5KnbexqOXVS69SfawPBZu0AVk-Tu_v/view?usp=sharing">downloaded here
        (~3.5GB)</a>.
</p>
</br>
<p>
    The full dataset is hosted on a publicly accessible S3 bucket and compressed into ~8.5GB chunks. To download it,
    you'll need to use the <a
        href="https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html">aws-cli</a>, and an
    LZMA-capable unzipping utility such as the <a href="https://packages.debian.org/sid/p7zip-full">7zip cli</a> to
    extract each zip file into its respective directory.

    Once installed, you can list out the dataset's components using:
<pre
    style="padding: 0;"><code class="language-bash">$ aws s3 ls --summarize --human-readable --recursive s3://public-datasets/challenges/reconstruction --endpoint=https://web.s3.wisc.edu --no-sign-request</code></pre>
</p>
</br>
<p>
    To download all the dataset archives to a predefined <span class="inline-code">$DOWNLOAD_DIR</span> in one shot, you
    can use the following command:
<pre
    style="padding: 0;"><code class="language-bash">$ aws s3 sync s3://public-datasets/challenges/reconstruction $DOWNLOAD_DIR --endpoint=https://web.s3.wisc.edu --no-sign-request</code></pre>

    If you wish to only download the test set, you can do so by appending <span class="inline-code">--exclude="*" --include="test*.zip"</span> to the above command.

You then need to extract all zips into their respective directories, which can be done with the following command in
bash:
<pre
    style="padding: 0;"><code class="language-bash">$ for zip in $(find $DOWNLOAD_DIR -type f -name "*.zip"); do 7z x $zip -o$(dirname $zip) && rm -f $zip; done</code></pre>
</p>
</br>
<p>
    For more single photon datasets, including real captures, <a href="https://github.com/wision-lab/datasets/">see
        here</a>.
</p>

{% endblock %}

templates/faq.html
{% extends "base.html" %}

{% block content %}

<link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/stackoverflow-dark.min.css" media="(prefers-color-scheme: dark)" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/stackoverflow-light.min.css" media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js"></script>
<script>hljs.highlightAll();</script>

<h3>Frequently Asked Questions</h3>

<h4>What is a single photon camera?</h4>
<p>
    Single photon cameras are an emerging class of sensors capable of detecting and counting individual photons at ultra-high speeds, reaching up to 100 kHz. You can read more about their <a href="https://visionsim.readthedocs.io/en/latest/sections/sensors/spcs/passive_spc.html">image formation model here.</a> 
</p>



<h4>How to register?</h4>
<p>
    In order to submit to the benchmark, you first need to register. Please note that in order to <a href="{% url 'download' %}">download</a> the dataset, no registration is needed. To register, first <a href="{% url 'core:signup' %}">create an account</a> and confirm your email address by clicking on the link we will send to you.
</p>



<h4>What format is the dataset stored as?</h4>
<p>
    The training set is structured as pairs of ground truth images and their associated photoncubes, namely <span class="inline-code">&lt;SCENE-NAME&gt;/&lt;FRAME-IDX&gt;.png</span> and <span class="inline-code">&lt;SCENE-NAME&gt;/&lt;FRAME-IDX&gt;.npy</span>. The photoncubes are encoded as width-wise bitpacked numpy arrays, with unpacked dimensions of (1024, 800, 800, 3). To read these, you can use numpy like so:
    <pre style="padding: 0;"><code class="language-python">import numpy as np 

# Load with memory mapping to avoid loading everything into RAM 
photoncube = np.load("datasets/train/attic/000000.npy", mmap_mode="r")
print(photoncube.shape)  # (1024, 800, 100, 3)

# Take first 10 binary frames 
bitplanes = np.unpackbits(photoncube[:10], axis=2)
print(bitplanes.shape)  # (10, 800, 800, 3)
</code></pre> 

    Importantly, ground truth reconstructions correspond to the <u><i>last frame</i></u> of each burst. In this case, <span class="inline-code">datasets/train/attic/000000.png</span> is the reconstruction of <span class="inline-code">np.unpackbits(photoncube[-1], axis=2)</span>. This ensures a causal context window, where each reconstruction only depends on previously captured single-photon data. 

    The test set is structured the same way, with the exception that ground truth reconstructions are not made public.   
</p>



<h4>How to submit my results to the benchmark?</h4>
<p>
    To submit your results to the benchmark, you need to zip them up into a single submission file. Importantly, the structure of this zip file should <u><i>exactly match</i></u> that of the test set. That is, the folder structure inside the zip file should be <span class="inline-code">&lt;SCENE-NAME&gt;/&lt;FRAME-IDX&gt;.png</span> without any other directories. All test samples, and nothing but the test samples, are expected and will be accepted.  
</p>

<h5>A naive implementation</h5>
<p>
    The simplest way to reconstruct an image from single-photon (binary) frames is to simply sum them up. We provide a simple implementation of this baseline here as a reference, feel free to run this locally to inspect the generated submission file, but please do not upload <span class="inline-code">naivesum</span> results, as these have already been evaluated <a href="{% url 'eval:reconstruction' %}">here</a>.   
</p>
<pre style="padding: 0;"><code class="language-python">from pathlib import Path
from zipfile import ZipFile

import numpy as np
import imageio.v3 as iio
from rich.progress import track

from visionsim.emulate.spc import spc_avg_to_rgb
from visionsim.utils.color import linearrgb_to_srgb


def naivesum(
    testset: Path,
    tonemap: bool = False,
    invert_response: bool = False,
    batch_size: int = 1024,
):
    with ZipFile("submission.zip", "w") as zipf:
        for binary_path in track(list(testset.glob("**/*.npy"))):
            with zipf.open(
                str(binary_path.with_suffix(".png").relative_to(testset)), "w"
            ) as f:
                # Unpack and average last few binary frames
                pc = np.load(binary_path)
                pc = np.unpackbits(pc[-batch_size:], axis=2)
                im = pc.sum(axis=0) / batch_size

                # Optionally invert the single photon camera's response 
                # function and tonemap the image back to sRGB  
                im = spc_avg_to_rgb(im, factor=0.5) if invert_response else im
                im = linearrgb_to_srgb(im) if tonemap else im

                # Convert to uint8 and save into zipfile
                im = (im * 255).astype(np.uint8)
                iio.imwrite(f, im, extension=".png")</code></pre>

<p>
    <u>Note:</u> We show how to directly save results into a zip here, but you can of course create the archive manually after the fact as well. 
</p>


<h4>Which metrics are used for evaluation?</h4>
<p>
    To evaluate reconstruction quality, we use <a href="https://lightning.ai/docs/torchmetrics/stable/image/peak_signal_noise_ratio.html">Peak Signal-to-Noise Ratio (PSNR)</a>, <a href="https://lightning.ai/docs/torchmetrics/stable/image/multi_scale_structural_similarity.html">Multi-Scale Structural Similarity Index Measure (MS-SSIM)</a>, and <a href="https://lightning.ai/docs/torchmetrics/stable/image/learned_perceptual_image_patch_similarity.html">Learned Perceptual Image Patch Similarity (LPIPS)</a>. For each metric, we compute the mean as well as the 5% and 1% quantiles to capture both average-case and worst-case performance. Note that for LPIPS, a lower score indicates better performance.
</p>


<h4>Can I benchmark my method without participating in the ongoing competition?</h4>
<p>
    Of course! You can always submit your results for evaluation and not participate in the competition. However, to participate in the competition, you must not only submit your results for evaluation here, but also submit additional information about your method. Competition guidelines can <a href="{% url 'competition' %}">be found here.</a>
</p>


<h4>Further Questions?</h4>
<p>
    If you find a website-related bug, please feel free to open a <a href="https://github.com/wision-lab/spcwebsite">Github issue here</a>. For other inquiries, please <a href="https://wisionlab.com/people/sacha-jungerman/">contact us here</a>.
</p>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<p>
    Welcome to the Single Photon Challenge website! Here you'll find large synthetic <a
        href="{% url 'download' %}">single photon datasets</a> that consist of bursts of single photon camera images and
    their corresponding ground truth reconstructions. There is also a <a href="{% url 'eval:reconstruction' %}">public
        leaderboard</a> showcasing various user-submitted reconstructions for this benchmark. You can <a
        href="{% url 'eval:compare' %}">directly compare</a> submissions as well!
</p>
</br>

<div class="teaserimg">
    <figure>
        <picture>
            <img src="{% static 'teaserimage.webp' %}" alt="Teaser image" fetchpriority="high" decoding="async">
        </picture>
        <figcaption>
            Single-photon cameras are capable of detecting individual photons, making them extremely sensitive,
            high-speed cameras. However, each image they capture is extremely noisy and binary valued, being dominated
            by photon shot noise. Given a burst of such binary frames, how can we recover a clean, high-fidelity image?
        </figcaption>
    </figure>
</div>

<h3>Ongoing Competition 📢</h3>
<p>
    <b>Reconstruction Competition:</b> Consider participating in the ongoing reconstruction competition for your chance
    to win thousands of dollars in prizes! Up to date competition guidelines can <a href="{% url 'competition' %}">be
        found here.</a></li>
</p>

<h3>News</h3>
<ul>
    <li>February 20, 2026: We identified a bug in the evaluation code that impacted the 5% and 1% metrics. As a result,
        submissions submitted before 2/20/26 have had these metrics removed. We encourage participants to resubmit their
        results for evaluation and, if desired, delete affected entries. Please note that missing metrics will not
        influence competition judging.</li>
    <li>February 19, 2026: New Feature! You can now click on the magnifying glass icon on a submission to see a
        zoomed-in side-by-side comparison.</li>
    <li>December 1, 2025: Fixed an issue that prevented some users from uploading their submissions from Windows
        machines. We thank early testers for letting us know about it.</li>
    <li>October 10, 2025: The dataset is now available <a href="{% url 'download' %}">here</a>! Check out the <a
            href="{% url 'faq' %}">FAQ</a> for instructions on how to submit.</li>
    <li>October 8, 2025: Hello world &ndash; this website is now live! The dataset is coming soon.</li>
</ul>

<h3>Citation</h3>
{% verbatim %}
<p>If you make use of our dataset or benchmark results, please cite:</p>
<pre><code>@software{visionsim,
    author = {Jungerman, Sacha and Gupta, Shantanu and Sadekar, Kaustubh and Leblang, Max and Gupta, Mohit},
    license = {MIT},
    month = may,
    title = {{visionsim}},
    url = {https://github.com/WISION-Lab/visionsim},
    year = {2025}
}
</code></pre>
{% endverbatim %}

{% endblock %}